repos:
- repo: https://github.com/fastai/nbdev
  rev: 2.2.10
  hooks:
  - id: nbdev_clean
    args: [--fname=./] # $PATH can be "./"
                       # having the root directory of the project suffices for all nbs in child directories to be succesfully cleaned
