repos:
- repo: local
  hooks:
  - id: nbdev_clean
    name: nbdev clean
    entry: nbdev_clean
    entry: python3 /gpfs01/berens/user/rgonzalesmarquez/.local/bin/nbdev_clean
    language: system
    pass_filenames: false

  # - id: nbdev_export
  #   name: nbdev export
  #   entry: /gpfs01/berens/user/rgonzalesmarquez/.local/bin/nbdev_export
  #   language: system
  #   pass_filenames: false